/* Generated By:JavaCC: Do not edit this line. gram_opcionesConstants.java */
package ANALIZADOR_OPCIONES;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface gram_opcionesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPCIONES_OPEN = 5;
  /** RegularExpression Id. */
  int OPCIONES_CLOSE = 6;
  /** RegularExpression Id. */
  int OPCION_OPEN = 7;
  /** RegularExpression Id. */
  int OPCION_CLOSE = 8;
  /** RegularExpression Id. */
  int NOMBRELISTA_OPEN = 9;
  /** RegularExpression Id. */
  int NOMBRELISTA_CLOSE = 10;
  /** RegularExpression Id. */
  int NOMBRE_OPEN = 11;
  /** RegularExpression Id. */
  int NOMBRE_CLOSE = 12;
  /** RegularExpression Id. */
  int ETIQUETA_OPEN = 13;
  /** RegularExpression Id. */
  int ETIQUETA_CLOSE = 14;
  /** RegularExpression Id. */
  int MULTIMEDIA_OPEN = 15;
  /** RegularExpression Id. */
  int MULTIMEDIA_CLOSE = 16;
  /** RegularExpression Id. */
  int VALOR = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"<opciones>\"",
    "\"</opciones>\"",
    "\"<opcion>\"",
    "\"</opcion>\"",
    "\"<nombre_lista>\"",
    "\"</nombre_lista>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<etiqueta>\"",
    "\"</etiqueta>\"",
    "\"<multimedia>\"",
    "\"</multimedia>\"",
    "<VALOR>",
  };

}
