/* Generated By:JavaCC: Do not edit this line. gram_opcionesConstants.java */
package ANALIZADOR_OPCIONES;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface gram_opcionesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOMBRE_LISTA = 1;
  /** RegularExpression Id. */
  int NOMBRE = 2;
  /** RegularExpression Id. */
  int ETIQUETA = 3;
  /** RegularExpression Id. */
  int MULTIMEDIA = 4;
  /** RegularExpression Id. */
  int LETRA = 5;
  /** RegularExpression Id. */
  int DIGITO = 6;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"nombre_lista\"",
    "\"nombre\"",
    "\"etiqueta\"",
    "\"multimedia\"",
    "<LETRA>",
    "<DIGITO>",
    "<IDENTIFICADOR>",
  };

}
