/* Generated By:JavaCC: Do not edit this line. Simple1.java */
package Analizador_Columnas;
import java.util.ArrayList;

public class Simple1 implements Simple1Constants {
    private static int CONT=-1;
    public String  initParser() throws ParseException, TokenMgrError
    {
        CONT=-1;
        return (contenido_etiqueta());
    }

/*-=-=-=-=-=-=-         SINTACTICO          -=-=-=-=-=-=-=-=-=-=-=-=-=*/
  final public String contenido_etiqueta() throws ParseException {
 String Cad;
    label_1:
    while (true) {
      Cad = CNT();
                   {if (true) return Cad;}
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ID:
      case Numeral:
      case Punto:
      case PuntoP:
      case Cualquiera:
      case string_literal:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
    }
    jj_consume_token(0);
    throw new Error("Missing return statement in function");
  }

  final public String CNT() throws ParseException {
 String Cad;
String aux;
    Cad = VALOR();
    aux = CNT_2();
                             Cad = Cad + aux;  {if (true) return Cad;}
    throw new Error("Missing return statement in function");
  }

  final public String CNT_2() throws ParseException {
 String Cad;
String aux;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID:
    case Numeral:
    case Punto:
    case PuntoP:
    case Cualquiera:
    case string_literal:
      Cad = VALOR();
      aux = CNT_2();
                              Cad = Cad + aux;  {if (true) return Cad;}
      break;
    case 0:
      jj_consume_token(0);
         {if (true) return "";}
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String VALOR() throws ParseException {
 Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Cualquiera:
      t = jj_consume_token(Cualquiera);
                                        CONT++;
                                        t.image = "\u005c"" + t.image + "\u005c"" + " ";
                                        if(CONT>0){
                                            t.image= "+" + t.image;
                                        }
                                        {if (true) return t.image;}
      break;
    case Numeral:
      jj_consume_token(Numeral);
      jj_consume_token(Acor);
      t = jj_consume_token(ID);
      jj_consume_token(Ccor);
                                        CONT++;
                                        if(CONT>0){
                                            t.image= "+" + t.image;
                                        }
                                        {if (true) return t.image + "().respuesta" ;}
      break;
    case Punto:
      jj_consume_token(Punto);
                                        CONT++;
                                        {if (true) return ".";}
      break;
    case PuntoP:
      jj_consume_token(PuntoP);
                                        CONT++;
                                        {if (true) return "posicion()";}
      break;
    case string_literal:
      t = jj_consume_token(string_literal);
                                        CONT++;
                                        if(CONT>0){
                                            t.image= "+" + t.image;
                                        }
                                        {if (true) return t.image;}
      break;
    case ID:
      t = jj_consume_token(ID);
                                        CONT++;
                                        t.image = "\u005c"" + t.image + "\u005c"";
                                        if(CONT>0){
                                            t.image= "+" + t.image;
                                        }
                                        {if (true) return t.image;}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public Simple1TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[3];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x1e50,0x1e51,0x1e50,};
   }

  /** Constructor with InputStream. */
  public Simple1(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Simple1(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new Simple1TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Simple1(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new Simple1TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Simple1(Simple1TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Simple1TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[14];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 3; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 14; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
