/* Generated By:JavaCC: Do not edit this line. Simple1Constants.java */
package Analizador_Columnas;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Simple1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 5;
  /** RegularExpression Id. */
  int Numeral = 6;
  /** RegularExpression Id. */
  int Acor = 7;
  /** RegularExpression Id. */
  int Ccor = 8;
  /** RegularExpression Id. */
  int Punto = 9;
  /** RegularExpression Id. */
  int PuntoP = 10;
  /** RegularExpression Id. */
  int Cualquiera = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "<ID>",
    "\"#\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"..\"",
    "<Cualquiera>",
  };

}
