/* Generated By:JavaCC: Do not edit this line. ParserConfigConstants.java */
package ANALIZADOR_CONFIGURACION;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConfigConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONFIGURACIONES_OPEN = 5;
  /** RegularExpression Id. */
  int CONFIGURACIONES_CLOSE = 6;
  /** RegularExpression Id. */
  int FILA_OPEN = 7;
  /** RegularExpression Id. */
  int FILA_CLOSE = 8;
  /** RegularExpression Id. */
  int TITULO_OPEN = 9;
  /** RegularExpression Id. */
  int TITULO_CLOSE = 10;
  /** RegularExpression Id. */
  int IDFORM_OPEN = 11;
  /** RegularExpression Id. */
  int IDFORM_CLOSE = 12;
  /** RegularExpression Id. */
  int ESTILO_OPEN = 13;
  /** RegularExpression Id. */
  int ESTILO_CLOSE = 14;
  /** RegularExpression Id. */
  int IMPORTAR_OPEN = 15;
  /** RegularExpression Id. */
  int IMPORTAR_CLOSE = 16;
  /** RegularExpression Id. */
  int CODMAIN_OPEN = 17;
  /** RegularExpression Id. */
  int CODMAIN_CLOSE = 18;
  /** RegularExpression Id. */
  int CODGLOB_OPEN = 19;
  /** RegularExpression Id. */
  int CODGLOB_CLOSE = 20;
  /** RegularExpression Id. */
  int VALOR = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"<configuraciones>\"",
    "\"</configuraciones>\"",
    "\"<fila>\"",
    "\"</fila>\"",
    "\"<titulo_formulario>\"",
    "\"</titulo_formulario>\"",
    "\"<idform>\"",
    "\"</idform>\"",
    "\"<estilo>\"",
    "\"</estilo>\"",
    "\"<importar>\"",
    "\"</importar>\"",
    "\"<codigo_principal>\"",
    "\"</codigo_principal>\"",
    "\"<codigo_global>\"",
    "\"</codigo_global>\"",
    "<VALOR>",
  };

}
