/* Generated By:JavaCC: Do not edit this line. ParserConfigTokenManager.java */
package ANALIZADOR_CONFIGURACION;
import Estructuras.*;
import java.util.ArrayList;

/** Token Manager. */
public class ParserConfigTokenManager implements ParserConfigConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 13:
         return jjMoveStringLiteralDfa1_0(0x4L);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x1fffe0L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 10:
         if ((active0 & 0x4L) != 0L)
            return jjStopAtPos(1, 2);
         break;
      case 47:
         return jjMoveStringLiteralDfa2_0(active0, 0x155540L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0xa0020L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa2_0(active0, 0x80L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x8800L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x140040L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x11280L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0xa0020L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0xa1000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa4_0(active0, 0x800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x500L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x80L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x20L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x140040L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x2200L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x80L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x140000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa5_0(active0, 0x1020L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0xa2000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x100L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x40L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x8800L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x4400L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(5, 7);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x100L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x40L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0xa0000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x144020L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x2200L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x11000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x8800L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(6, 8);
         break;
      case 71:
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0x140020L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x40L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x4400L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x800L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0xa2200L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x11000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x800L) != 0L)
            return jjStopAtPos(7, 11);
         else if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(7, 13);
         break;
      case 95:
         return jjMoveStringLiteralDfa8_0(active0, 0xa0200L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa8_0(active0, 0x40L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x144400L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(8, 12);
         else if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(8, 14);
         break;
      case 95:
         return jjMoveStringLiteralDfa9_0(active0, 0x140400L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa9_0(active0, 0x200L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x8020L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa9_0(active0, 0x40L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(9, 15);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa10_0(active0, 0x20L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa10_0(active0, 0x400L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x200L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa10_0(active0, 0x40000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0x30040L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(10, 16);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x40L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa11_0(active0, 0x20L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa11_0(active0, 0x100000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa11_0(active0, 0x80400L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa11_0(active0, 0x40200L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa12_0(active0, 0x80000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa12_0(active0, 0x40L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x40020L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa12_0(active0, 0x200L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x20000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa12_0(active0, 0x100000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa12_0(active0, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa13_0(active0, 0x80000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa13_0(active0, 0x100000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa13_0(active0, 0x20000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x40L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa13_0(active0, 0x400L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa13_0(active0, 0x40000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa13_0(active0, 0x20L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa13_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0);
      return 13;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa14_0(active0, 0x100000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa14_0(active0, 0x40000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa14_0(active0, 0x20000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa14_0(active0, 0x80200L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa14_0(active0, 0x20L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa14_0(active0, 0x40L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa14_0(active0, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0);
      return 14;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(14, 19);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa15_0(active0, 0x200L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa15_0(active0, 0x20L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa15_0(active0, 0x40000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa15_0(active0, 0x100400L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa15_0(active0, 0x40L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa15_0(active0, 0x20000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0);
      return 15;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(15, 20);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa16_0(active0, 0x20400L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa16_0(active0, 0x40L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa16_0(active0, 0x40000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa16_0(active0, 0x200L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa16_0(active0, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0);
      return 16;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(16, 5);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa17_0(active0, 0x40000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa17_0(active0, 0x200L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa17_0(active0, 0x20000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa17_0(active0, 0x400L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa17_0(active0, 0x40L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0);
}
private int jjMoveStringLiteralDfa17_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(15, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, active0);
      return 17;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(17, 6);
         else if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(17, 17);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa18_0(active0, 0x400L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa18_0(active0, 0x40000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa18_0(active0, 0x200L);
      default :
         break;
   }
   return jjStartNfa_0(16, active0);
}
private int jjMoveStringLiteralDfa18_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(16, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(17, active0);
      return 18;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(18, 9);
         else if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(18, 18);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa19_0(active0, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(17, active0);
}
private int jjMoveStringLiteralDfa19_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(17, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(18, active0);
      return 19;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x400L) != 0L)
            return jjStopAtPos(19, 10);
         break;
      default :
         break;
   }
   return jjStartNfa_0(18, active0);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 3;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  jjAddStates(0, 1);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if (curChar == 126)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 1:
                  if ((0xbfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(1, 2);
                  break;
               case 2:
                  if (curChar == 126 && kind > 21)
                     kind = 21;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(0, 1);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 3 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   1, 2, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3fffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[3];
private final int[] jjstateSet = new int[6];
protected char curChar;
/** Constructor. */
public ParserConfigTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public ParserConfigTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 3; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
