/* Generated By:JavaCC: Do not edit this line. ParserParamConstants.java */
package Analizador_Parametros;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserParamConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CADMIN = 5;
  /** RegularExpression Id. */
  int CADMAX = 6;
  /** RegularExpression Id. */
  int INICIAR = 7;
  /** RegularExpression Id. */
  int FINALIZAR = 8;
  /** RegularExpression Id. */
  int CADFILA = 9;
  /** RegularExpression Id. */
  int IG_IG = 10;
  /** RegularExpression Id. */
  int ENTERO = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"cad_min\"",
    "\"cad_max\"",
    "\"iniciar\"",
    "\"finalizar\"",
    "\"cad_fila\"",
    "\"=\"",
    "<ENTERO>",
  };

}
