
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 17 21:11:37 CST 2018
//----------------------------------------------------

package ANALIZADORES.LenguajeD_PP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 2;
  public static final int POT = 10;
  public static final int ESTRUCT = 39;
  public static final int POR = 8;
  public static final int IMPRIMIR = 50;
  public static final int SI = 43;
  public static final int ENTERO = 34;
  public static final int CPAR = 14;
  public static final int MAYQ = 26;
  public static final int CLLA = 16;
  public static final int PRINCIPAL = 52;
  public static final int NOT = 31;
  public static final int AND = 30;
  public static final int MENQ = 24;
  public static final int IGUAL = 22;
  public static final int SINO = 44;
  public static final int CARACTER = 33;
  public static final int APAR = 13;
  public static final int OR = 29;
  public static final int MIENTRAS = 45;
  public static final int INC = 11;
  public static final int DIV = 9;
  public static final int ALLA = 15;
  public static final int CONTINUAR = 48;
  public static final int ID = 5;
  public static final int SIGNO_Q = 42;
  public static final int PTO = 41;
  public static final int DECIMAL = 35;
  public static final int EOF = 0;
  public static final int CUADRADO = 54;
  public static final int ACORCH = 17;
  public static final int OVALO = 55;
  public static final int error = 1;
  public static final int CCORCH = 18;
  public static final int NULO = 40;
  public static final int COMA = 19;
  public static final int MENIQ = 25;
  public static final int CADENA = 32;
  public static final int DIF = 28;
  public static final int MENOS = 7;
  public static final int IG_IG = 23;
  public static final int MAYIQ = 27;
  public static final int NUM_LITERAL = 3;
  public static final int DETENER = 47;
  public static final int PUNTO = 53;
  public static final int VACIO = 51;
  public static final int FALSO = 37;
  public static final int DECIMAL_LITERAL = 4;
  public static final int BOOLEANO = 36;
  public static final int PARA = 46;
  public static final int RETORNAR = 49;
  public static final int VERDADERO = 38;
  public static final int DEC = 12;
  public static final int DSPTS = 21;
  public static final int LINEA = 56;
  public static final int PYC = 20;
  public static final int MAS = 6;
}

