/* Generated By:JavaCC: Do not edit this line. ParserOtrasConstants.java */
package Analizador_OtrasColumnas;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserOtrasConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 4;
  /** RegularExpression Id. */
  int Numeral = 5;
  /** RegularExpression Id. */
  int Acor = 6;
  /** RegularExpression Id. */
  int Ccor = 7;
  /** RegularExpression Id. */
  int Punto = 8;
  /** RegularExpression Id. */
  int PuntoP = 9;
  /** RegularExpression Id. */
  int Cualquiera = 10;
  /** RegularExpression Id. */
  int string_literal = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "<ID>",
    "\"#\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"..\"",
    "<Cualquiera>",
    "<string_literal>",
    "\" \"",
  };

}
