/* Generated By:JavaCC: Do not edit this line. ParserMultimediaConstants.java */
package Analizador_ColumnaMultimedia;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserMultimediaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TRUE = 5;
  /** RegularExpression Id. */
  int IG_IG = 6;
  /** RegularExpression Id. */
  int FALSE = 7;
  /** RegularExpression Id. */
  int M_IMG = 8;
  /** RegularExpression Id. */
  int M_VID = 9;
  /** RegularExpression Id. */
  int M_AUD = 10;
  /** RegularExpression Id. */
  int REPRO = 11;
  /** RegularExpression Id. */
  int string_literal = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "<TRUE>",
    "\"=\"",
    "<FALSE>",
    "\"media_imagen\"",
    "\"media_video\"",
    "\"media_audio\"",
    "\"reproduccion\"",
    "<string_literal>",
  };

}
