/* Generated By:JavaCC: Do not edit this line. gramaticaConstants.java */
package ANALIZADOR_JAVACC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface gramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TIPO = 1;
  /** RegularExpression Id. */
  int IDPREGUNTA = 2;
  /** RegularExpression Id. */
  int ETIQUETA = 3;
  /** RegularExpression Id. */
  int SUGERIR = 4;
  /** RegularExpression Id. */
  int CODIGO_PRE = 5;
  /** RegularExpression Id. */
  int CODIGO_POST = 6;
  /** RegularExpression Id. */
  int RESTRINGIR = 7;
  /** RegularExpression Id. */
  int RESTRINGIRMSN = 8;
  /** RegularExpression Id. */
  int REQUERIDO = 9;
  /** RegularExpression Id. */
  int REQUERIDOMSN = 10;
  /** RegularExpression Id. */
  int PREDETERMINADO = 11;
  /** RegularExpression Id. */
  int APLICABLE = 12;
  /** RegularExpression Id. */
  int LECTURA = 13;
  /** RegularExpression Id. */
  int CALCULO = 14;
  /** RegularExpression Id. */
  int REPETICION = 15;
  /** RegularExpression Id. */
  int MULTIMEDIA = 16;
  /** RegularExpression Id. */
  int APARIENCIA = 17;
  /** RegularExpression Id. */
  int PARAMETRO = 18;
  /** RegularExpression Id. */
  int NOMBRE_LISTA = 19;
  /** RegularExpression Id. */
  int NOMBRE = 20;
  /** RegularExpression Id. */
  int TITULO_FORMULARIO = 21;
  /** RegularExpression Id. */
  int IDFOM = 22;
  /** RegularExpression Id. */
  int ESTILO = 23;
  /** RegularExpression Id. */
  int IMPORTAR = 24;
  /** RegularExpression Id. */
  int CODIGO_PRINCIPAL = 25;
  /** RegularExpression Id. */
  int CODIGO_GLOBAL = 26;
  /** RegularExpression Id. */
  int PAGINA = 27;
  /** RegularExpression Id. */
  int TODO = 28;
  /** RegularExpression Id. */
  int CUADRICULA = 29;
  /** RegularExpression Id. */
  int ENCUESTA = 30;
  /** RegularExpression Id. */
  int PREGUNTA_OPEN = 31;
  /** RegularExpression Id. */
  int PREGUNTA_CLOSE = 32;
  /** RegularExpression Id. */
  int SEPARADOR = 33;
  /** RegularExpression Id. */
  int APAR = 34;
  /** RegularExpression Id. */
  int CPAR = 35;
  /** RegularExpression Id. */
  int ALLA = 36;
  /** RegularExpression Id. */
  int CLLA = 37;
  /** RegularExpression Id. */
  int COMA = 38;
  /** RegularExpression Id. */
  int PYC = 39;
  /** RegularExpression Id. */
  int DSPTS = 40;
  /** RegularExpression Id. */
  int PTO = 41;
  /** RegularExpression Id. */
  int IG_IG = 42;
  /** RegularExpression Id. */
  int IGUAL = 43;
  /** RegularExpression Id. */
  int DIF = 44;
  /** RegularExpression Id. */
  int MENQ = 45;
  /** RegularExpression Id. */
  int MAYQ = 46;
  /** RegularExpression Id. */
  int MENIQ = 47;
  /** RegularExpression Id. */
  int MAYIQ = 48;
  /** RegularExpression Id. */
  int SUCC = 49;
  /** RegularExpression Id. */
  int DECC = 50;
  /** RegularExpression Id. */
  int MAS = 51;
  /** RegularExpression Id. */
  int MENOS = 52;
  /** RegularExpression Id. */
  int POR = 53;
  /** RegularExpression Id. */
  int DIV = 54;
  /** RegularExpression Id. */
  int POT = 55;
  /** RegularExpression Id. */
  int NOT = 56;
  /** RegularExpression Id. */
  int AND = 57;
  /** RegularExpression Id. */
  int OR = 58;
  /** RegularExpression Id. */
  int COM_S = 59;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 60;
  /** RegularExpression Id. */
  int NUMBER = 61;
  /** RegularExpression Id. */
  int ID = 62;
  /** RegularExpression Id. */
  int VAR = 63;
  /** RegularExpression Id. */
  int STRING = 64;
  /** RegularExpression Id. */
  int CHA_R = 65;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"tipo\"",
    "\"idpregunta\"",
    "\"etiqueta\"",
    "\"sugerir\"",
    "\"codigo_pre\"",
    "\"codigo_post\"",
    "\"restringir\"",
    "\"restringirmsn\"",
    "\"requerido\"",
    "\"requeridomsn\"",
    "\"predeterminado\"",
    "\"aplicable\"",
    "\"lectura\"",
    "\"calculo\"",
    "\"repeticion\"",
    "\"multimedia\"",
    "\"apariencia\"",
    "\"parametro\"",
    "\"nombre_lista\"",
    "\"nombre\"",
    "\"titulo_formulario\"",
    "\"idform\"",
    "\"estilo\"",
    "\"importar\"",
    "\"codigo_principal\"",
    "\"codigo_global\"",
    "\"pagina\"",
    "\"todo\"",
    "\"cuadricula\"",
    "\"encuesta\"",
    "\"p~r~egunta\"",
    "\"pr~egu~nt~a\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "\"==\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"!\"",
    "\"&&\"",
    "\"||\"",
    "\"\\\'\"",
    "<BOOLEAN_LITERAL>",
    "<NUMBER>",
    "<ID>",
    "<VAR>",
    "<STRING>",
    "<CHA_R>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
  };

}
