/* Generated By:JavaCC: Do not edit this line. gramaticaTokenManager.java */
package ANALIZADOR_JAVACC;
import Estructuras.*;
import java.util.*;

/** Token Manager. */
public class gramaticaTokenManager implements gramaticaConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1fffffffeL) != 0L)
         {
            jjmatchedKind = 62;
            return 17;
         }
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 65;
            return -1;
         }
         return -1;
      case 1:
         if ((active0 & 0x200000000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 65;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x17ffffffeL) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 1;
            return 17;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 2:
         if ((active0 & 0x100000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x7ffffffeL) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 2;
            return 17;
         }
         return -1;
      case 3:
         if ((active0 & 0x6ffffffcL) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 3;
            return 17;
         }
         if ((active0 & 0x100000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x10000002L) != 0L)
            return 17;
         return -1;
      case 4:
         if ((active0 & 0x100000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x6ffffffcL) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 4;
            return 17;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      case 5:
         if ((active0 & 0x100000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x6727fffcL) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 5;
            }
            return 17;
         }
         if ((active0 & 0x8d80000L) != 0L)
            return 17;
         return -1;
      case 6:
         if ((active0 & 0x100000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x6010L) != 0L)
            return 17;
         if ((active0 & 0x672f9fecL) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 6;
            return 17;
         }
         return -1;
      case 7:
         if ((active0 & 0x262f9fe4L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 7;
            return 17;
         }
         if ((active0 & 0x100000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x41000008L) != 0L)
            return 17;
         return -1;
      case 8:
         if ((active0 & 0x100000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x262b89e4L) != 0L)
         {
            if (jjmatchedPos != 8)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 8;
            }
            return 17;
         }
         if ((active0 & 0x41600L) != 0L)
            return 17;
         return -1;
      case 9:
         if ((active0 & 0x100000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x200381a4L) != 0L)
            return 17;
         if ((active0 & 0x6280c40L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 9;
            }
            return 17;
         }
         return -1;
      case 10:
         if ((active0 & 0x100000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 62;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x6280d00L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 10;
            return 17;
         }
         if ((active0 & 0x40L) != 0L)
            return 17;
         return -1;
      case 11:
         if ((active0 & 0x80400L) != 0L)
            return 17;
         if ((active0 & 0x6200900L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 11;
            return 17;
         }
         return -1;
      case 12:
         if ((active0 & 0x2200800L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 12;
            return 17;
         }
         if ((active0 & 0x4000100L) != 0L)
            return 17;
         return -1;
      case 13:
         if ((active0 & 0x2200000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 13;
            return 17;
         }
         if ((active0 & 0x800L) != 0L)
            return 17;
         return -1;
      case 14:
         if ((active0 & 0x2200000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 14;
            return 17;
         }
         return -1;
      case 15:
         if ((active0 & 0x2000000L) != 0L)
            return 17;
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 15;
            return 17;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 69);
      case 13:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8L);
      case 33:
         jjmatchedKind = 56;
         return jjMoveStringLiteralDfa1_0(0x100000000000L, 0x0L);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x200000000000000L, 0x0L);
      case 39:
         return jjStopAtPos(0, 59);
      case 40:
         return jjStopAtPos(0, 34);
      case 41:
         return jjStopAtPos(0, 35);
      case 42:
         return jjStopAtPos(0, 53);
      case 43:
         jjmatchedKind = 51;
         return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0x0L);
      case 44:
         return jjStopAtPos(0, 38);
      case 45:
         jjmatchedKind = 52;
         return jjMoveStringLiteralDfa1_0(0x4000000000000L, 0x0L);
      case 46:
         return jjStopAtPos(0, 41);
      case 47:
         return jjStopAtPos(0, 54);
      case 58:
         return jjStopAtPos(0, 40);
      case 59:
         return jjStopAtPos(0, 39);
      case 60:
         jjmatchedKind = 45;
         return jjMoveStringLiteralDfa1_0(0x800000000000L, 0x0L);
      case 61:
         jjmatchedKind = 43;
         return jjMoveStringLiteralDfa1_0(0x40000000000L, 0x0L);
      case 62:
         jjmatchedKind = 46;
         return jjMoveStringLiteralDfa1_0(0x1000000000000L, 0x0L);
      case 94:
         return jjStopAtPos(0, 55);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x21000L, 0x0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x26004060L, 0x0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x40800008L, 0x0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1400004L, 0x0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x2000L, 0x0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x10000L, 0x0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x180000L, 0x0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x188040800L, 0x0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x8780L, 0x0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x10L, 0x0L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x10200002L, 0x0L);
      case 123:
         return jjStopAtPos(0, 36);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x400000000000000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 37);
      case 126:
         return jjStopAtPos(0, 33);
      default :
         return jjMoveNfa_0(8, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 10:
         if ((active1 & 0x8L) != 0L)
            return jjStopAtPos(1, 67);
         break;
      case 38:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStopAtPos(1, 57);
         break;
      case 43:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStopAtPos(1, 49);
         break;
      case 45:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 50);
         break;
      case 61:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 42);
         else if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 44);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStopAtPos(1, 47);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(1, 48);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8044000L, active1, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x400004L, active1, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0xa780L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x200002L, active1, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x16180060L, active1, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x21000L, active1, 0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000800L, active1, 0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L, active1, 0L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x8L, active1, 0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x20010010L, active1, 0L);
      case 124:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStopAtPos(1, 58);
         break;
      case 126:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, 0L);
      return 2;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x20020000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x40002000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x16000060L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000010L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x8L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x15000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x180000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x1008006L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0x600L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x80040000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x180L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0xa00000L);
      case 126:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, 0L);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x180000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000800L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x100008010L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0xe801060L);
      case 79:
      case 111:
         if ((active0 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(3, 1, 17);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(3, 28, 17);
         return jjMoveStringLiteralDfa4_0(active0, 0x1400000L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa4_0(active0, 0x8L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x20004L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x12180L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x40200600L);
      case 126:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, 0L);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0xc0000e04L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x106000060L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x30000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0xa00000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x21580190L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x6008L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(5, 27, 17);
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 69:
      case 101:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0xe0008L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000004L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x20008190L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000L);
      case 77:
      case 109:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(5, 22, 17);
         return jjMoveStringLiteralDfa6_0(active0, 0x10000L);
      case 79:
      case 111:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 23, 17);
         return jjMoveStringLiteralDfa6_0(active0, 0x6200060L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x2600L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000800L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa7_0(active0, 0x6280060L);
      case 65:
      case 97:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(6, 13, 17);
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x20008000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0x10800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x600L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa7_0(active0, 0x20180L);
      case 79:
      case 111:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(6, 14, 17);
         break;
      case 82:
      case 114:
         if ((active0 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(6, 4, 17);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x40040008L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000004L);
      case 126:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(7, 3, 17);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(7, 30, 17);
         break;
      case 67:
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa8_0(active0, 0x10600L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000180L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x81000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa8_0(active0, 0x180000004L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000060L);
      case 82:
      case 114:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(7, 24, 17);
         return jjMoveStringLiteralDfa8_0(active0, 0x40800L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(8, 12, 17);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0xb0180L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x24000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa9_0(active0, 0x800L);
      case 79:
      case 111:
         if ((active0 & 0x200L) != 0L)
         {
            jjmatchedKind = 9;
            jjmatchedPos = 8;
         }
         else if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(8, 18, 17);
         return jjMoveStringLiteralDfa9_0(active0, 0x208440L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000020L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x180000004L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(9, 2, 17);
         else if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(9, 16, 17);
         else if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(9, 17, 17);
         else if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(9, 29, 17);
         else if ((active0 & 0x80000000L) != 0L)
            return jjStopAtPos(9, 31);
         break;
      case 69:
      case 101:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(9, 5, 17);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000800L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa10_0(active0, 0x400L);
      case 78:
      case 110:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(9, 15, 17);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000L);
      case 82:
      case 114:
         if ((active0 & 0x80L) != 0L)
         {
            jjmatchedKind = 7;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x200100L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa10_0(active0, 0x80040L);
      case 126:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(10, 32);
         break;
      case 66:
      case 98:
         return jjMoveStringLiteralDfa11_0(active0, 0x4000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa11_0(active0, 0x200100L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0x2000800L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa11_0(active0, 0x400L);
      case 84:
      case 116:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(10, 6, 17);
         return jjMoveStringLiteralDfa11_0(active0, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(11, 19, 17);
         return jjMoveStringLiteralDfa12_0(active0, 0x4000800L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa12_0(active0, 0x2000000L);
      case 78:
      case 110:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(11, 10, 17);
         break;
      case 83:
      case 115:
         return jjMoveStringLiteralDfa12_0(active0, 0x100L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, 0L);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa13_0(active0, 0x800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000000L);
      case 76:
      case 108:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(12, 26, 17);
         return jjMoveStringLiteralDfa13_0(active0, 0x200000L);
      case 78:
      case 110:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(12, 8, 17);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa14_0(active0, 0x200000L);
      case 79:
      case 111:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(13, 11, 17);
         break;
      case 80:
      case 112:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa15_0(active0, 0x2000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa15_0(active0, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(13, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0, 0L);
      return 15;
   }
   switch(curChar)
   {
      case 73:
      case 105:
         return jjMoveStringLiteralDfa16_0(active0, 0x200000L);
      case 76:
      case 108:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(15, 25, 17);
         break;
      default :
         break;
   }
   return jjStartNfa_0(14, active0, 0L);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(14, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0, 0L);
      return 16;
   }
   switch(curChar)
   {
      case 79:
      case 111:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(16, 21, 17);
         break;
      default :
         break;
   }
   return jjStartNfa_0(15, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 25;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 8:
                  if ((0xfff800000000L & l) != 0L)
                  {
                     if (kind > 65)
                        kind = 65;
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 61)
                        kind = 61;
                     jjCheckNAddTwoStates(13, 14);
                  }
                  else if (curChar == 34)
                     jjCheckNAddTwoStates(22, 23);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  jjCheckNAddTwoStates(13, 14);
                  break;
               case 14:
                  if (curChar == 46)
                     jjCheckNAdd(15);
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  jjCheckNAdd(15);
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 21:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(22, 23);
                  break;
               case 22:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(22, 23);
                  break;
               case 23:
                  if (curChar == 34 && kind > 64)
                     kind = 64;
                  break;
               case 24:
                  if ((0xfff800000000L & l) != 0L && kind > 65)
                     kind = 65;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 8:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 62)
                        kind = 62;
                     jjCheckNAdd(17);
                  }
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 19;
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  else if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 0:
                  if ((0x800000008000L & l) != 0L && kind > 60)
                     kind = 60;
                  break;
               case 1:
                  if ((0x4000000040000L & l) != 0L)
                     jjCheckNAdd(0);
                  break;
               case 2:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 9:
                  if ((0x8000000080000L & l) != 0L)
                     jjCheckNAdd(0);
                  break;
               case 10:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 16:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  jjCheckNAdd(17);
                  break;
               case 17:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  jjCheckNAdd(17);
                  break;
               case 18:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(20);
                  break;
               case 20:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(20);
                  break;
               case 22:
                  jjAddStates(0, 1);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 22:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(0, 1);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 25 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   22, 23, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, "\176", "\50", "\51", "\173", "\175", "\54", 
"\73", "\72", "\56", "\75\75", "\75", "\41\75", "\74", "\76", "\74\75", "\76\75", 
"\53\53", "\55\55", "\53", "\55", "\52", "\57", "\136", "\41", "\46\46", "\174\174", 
"\47", null, null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffffffffL, 0x3L, 
};
static final long[] jjtoSkip = {
   0x0L, 0x3cL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[25];
private final int[] jjstateSet = new int[50];
private final StringBuilder jjimage = new StringBuilder();
private StringBuilder image = jjimage;
private int jjimageLen;
private int lengthOfMatch;
protected char curChar;
/** Constructor. */
public gramaticaTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public gramaticaTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 25; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100000200L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         SkipLexicalActions(null);
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 69 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          System.out.println("saltando");
         break;
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
