/* Generated By:JavaCC: Do not edit this line. ParserEncuestaConstants.java */
package Analizador_Encuesta;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserEncuestaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENCUESTA_OPEN = 5;
  /** RegularExpression Id. */
  int ENCUESTA_CLOSE = 6;
  /** RegularExpression Id. */
  int PREGUNTA_OPEN = 7;
  /** RegularExpression Id. */
  int PREGUNTA_CLOSE = 8;
  /** RegularExpression Id. */
  int TIPO_OPEN = 9;
  /** RegularExpression Id. */
  int TIPO_CLOSE = 10;
  /** RegularExpression Id. */
  int CUALQUIERA = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"e~ncu~esta\"",
    "\"en~cues~ta\"",
    "\"p~r~egunta\"",
    "\"pr~egu~nt~a\"",
    "\"tip~o\"",
    "\"~ti~po\"",
    "<CUALQUIERA>",
  };

}
