/* Generated By:JavaCC: Do not edit this line. ParserEncuestaConstants.java */
package Analizador_Encuestas;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserEncuestaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENCUESTA_OPEN = 5;
  /** RegularExpression Id. */
  int ENCUESTA_CLOSE = 6;
  /** RegularExpression Id. */
  int PREGUNTA_OPEN = 7;
  /** RegularExpression Id. */
  int PREGUNTA_CLOSE = 8;
  /** RegularExpression Id. */
  int IDPREGUNTA_OPEN = 9;
  /** RegularExpression Id. */
  int IDPREGUNTA_CLOSE = 10;
  /** RegularExpression Id. */
  int ETIQUETA_OPEN = 11;
  /** RegularExpression Id. */
  int ETIQUETA_CLOSE = 12;
  /** RegularExpression Id. */
  int SUGERIR_OPEN = 13;
  /** RegularExpression Id. */
  int SUGERIR_CLOSE = 14;
  /** RegularExpression Id. */
  int CODIGOPRE_OPEN = 15;
  /** RegularExpression Id. */
  int CODIGOPRE_CLOSE = 16;
  /** RegularExpression Id. */
  int CODIGOPOST_OPEN = 17;
  /** RegularExpression Id. */
  int CODIGOPOST_CLOSE = 18;
  /** RegularExpression Id. */
  int RESTRINGIR_OPEN = 19;
  /** RegularExpression Id. */
  int RESTRINGIR_CLOSE = 20;
  /** RegularExpression Id. */
  int RESTRINGIRMSN_OPEN = 21;
  /** RegularExpression Id. */
  int RESTRINGIRMSN_CLOSE = 22;
  /** RegularExpression Id. */
  int REQUERIDO_OPEN = 23;
  /** RegularExpression Id. */
  int REQUERIDO_CLOSE = 24;
  /** RegularExpression Id. */
  int REQUERIDOMSN_OPEN = 25;
  /** RegularExpression Id. */
  int REQUERIDOMSN_CLOSE = 26;
  /** RegularExpression Id. */
  int PREDETERMINADO_OPEN = 27;
  /** RegularExpression Id. */
  int PREDETERMINADO_CLOSE = 28;
  /** RegularExpression Id. */
  int APLICABLE_OPEN = 29;
  /** RegularExpression Id. */
  int APLICABLE_CLOSE = 30;
  /** RegularExpression Id. */
  int LECTURA_OPEN = 31;
  /** RegularExpression Id. */
  int LECTURA_CLOSE = 32;
  /** RegularExpression Id. */
  int CALCULO_OPEN = 33;
  /** RegularExpression Id. */
  int CALCULO_CLOSE = 34;
  /** RegularExpression Id. */
  int REPETICION_OPEN = 35;
  /** RegularExpression Id. */
  int REPETICION_CLOSE = 36;
  /** RegularExpression Id. */
  int MULTIMEDIA_OPEN = 37;
  /** RegularExpression Id. */
  int MULTIMEDIA_CLOSE = 38;
  /** RegularExpression Id. */
  int APARIENCIA_OPEN = 39;
  /** RegularExpression Id. */
  int APARIENCIA_CLOSE = 40;
  /** RegularExpression Id. */
  int PARAMETRO_OPEN = 41;
  /** RegularExpression Id. */
  int PARAMETRO_CLOSE = 42;
  /** RegularExpression Id. */
  int TIPO_OPEN = 43;
  /** RegularExpression Id. */
  int TIPO_CLOSE = 44;
  /** RegularExpression Id. */
  int VALOR = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"<encuesta>\"",
    "\"</encuesta>\"",
    "\"<pregunta>\"",
    "\"</pregunta>\"",
    "\"<idpregunta>\"",
    "\"</idpregunta>\"",
    "\"<etiqueta>\"",
    "\"</etiqueta>\"",
    "\"<sugerir>\"",
    "\"</sugerir>\"",
    "\"<codigo_pre>\"",
    "\"</codigo_pre>\"",
    "\"<codigo_post>\"",
    "\"</codigo_post>\"",
    "\"<restringir>\"",
    "\"</restringir>\"",
    "\"<restringirmsn>\"",
    "\"</restringirmsn>\"",
    "\"<requerido>\"",
    "\"</requerido>\"",
    "\"<requeridomsn>\"",
    "\"</requeridomsn>\"",
    "\"<predeterminado>\"",
    "\"</predeterminado>\"",
    "\"<aplicable>\"",
    "\"</aplicable>\"",
    "\"<lectura>\"",
    "\"</lectura>\"",
    "\"<calculo>\"",
    "\"</calculo>\"",
    "\"<repeticion>\"",
    "\"</repeticion>\"",
    "\"<multimedia>\"",
    "\"</multimedia>\"",
    "\"<apariencia>\"",
    "\"</apariencia>\"",
    "\"<parametro>\"",
    "\"</parametro>\"",
    "\"<tipo>\"",
    "\"</tipo>\"",
    "<VALOR>",
  };

}
